Repository Kirushka-png/Lab-6, pull requests merged in 2020-06, with the labels that each got.

#7 Библиотека
  PythonApplication1.sln
  PythonApplication1/PythonApplication1.py
  PythonApplication1/PythonApplication1.pyproj
  PythonApplication1/class1.py
Labels: trpo, visual studio

#9 Update .travis.yml
  .travis.yml
Labels: ci, trpo

#10 for release
  .travis.yml
Labels: ci, trpo

#11 Release
  .travis.yml
  PythonApplication1.sln
  PythonApplication1/PythonApplication1.py
  PythonApplication1/PythonApplication1.pyproj
  PythonApplication1/class1.py
  PythonApplication1/test_auth.py
Labels: ci, trpo

#12 Pre-release
  .travis.yml
Labels: ci, trpo

#14 Update README.md
  README.md
Labels: ci

#15 Issue 6
  .travis.yml
  .travis/default.yml
  .travis/release.yml
Labels: ci, trpo

#16 Dev
  .travis.yml
  .travis/default.yml
  .travis/release.yml
  README.md
Labels: ci, trpo

#18 Issue 6
  .travis.yml
Labels: ci, trpo
